/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\assets\porsche_gt3_rs.glb 
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-gt3-rs-e738eae819c34d19a31dd066c45e0f3d
Title: Porsche GT3 RS
*/
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import { useFrame } from "@react-three/fiber";

export function Porsche(props) {
  const { wireframe } = useControls({
    wireframe: false,
  });

  const { nodes, materials } = useGLTF("models/porscheV2.glb");
  const wireframeRef = useRef();
  const texturedRef = useRef();
  const porscheRef = useRef();
  const [progress, setProgress] = useState(50);

  useFrame(() => {
    setProgress((prev) => (prev + 0.01) % 1); // Increment progress
    if (wireframeRef.current && texturedRef.current) {
      updateGeometries(wireframeRef.current, texturedRef.current, progress);
    }

    if(porscheRef.current){
      porscheRef.current.rotation.y += 0.002;
    }
  });

  useEffect(() => {
    if (wireframeRef.current && texturedRef.current) {
      updateGeometries(wireframeRef.current, texturedRef.current, progress);
    }
  }, [nodes]);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe]);

  return (
    <group {...props} dispose={null} ref={porscheRef} position={[0, 0, -1]}>
    <group scale={0.008}>
      <group
        position={[0, 0, 0]} // Centered position
        rotation={[0, 0, 0]}
        scale={100}
      >
            <mesh geometry={nodes.porsche_1.geometry} material={materials['TwiXeR_992_gauges_screen.001']} />
          <mesh geometry={nodes.porsche_2.geometry} material={materials['TwiXeR_992_plastic_mgl_060606FF.001']} />
          <mesh geometry={nodes.porsche_3.geometry} material={materials['TwiXeR_992_carPaint.003']} />
          <mesh geometry={nodes.porsche_4.geometry} material={materials['TwiXeR_992_headlight_1.001']} />
          <mesh geometry={nodes.porsche_5.geometry} material={materials['TwiXeR_992_carbon_roof.001']} />
          <mesh geometry={nodes.porsche_6.geometry} material={materials['TwiXeR_992_metal_radiator.002']} />
          <mesh geometry={nodes.porsche_7.geometry} material={materials['TwiXeR_992_headlight_1.001_0']} />
          <mesh geometry={nodes.porsche_8.geometry} material={materials['TwiXeR_992_glass.002']} />
          <mesh geometry={nodes.porsche_9.geometry} material={materials['TwiXeR_992_symbols.004']} />
          <mesh geometry={nodes.porsche_10.geometry} material={materials['TwiXeR_992_antichrome.001']} />
          <mesh geometry={nodes.porsche_11.geometry} material={materials['TwiXeR_992_red.001']} />
          <mesh geometry={nodes.porsche_12.geometry} material={materials['TwiXeR_992_headlight_1.001_1']} />
          <mesh geometry={nodes.porsche_13.geometry} material={materials['TwiXeR_992_plastic_mgl.001']} />
          <mesh geometry={nodes.porsche_14.geometry} material={materials['TwiXeR_992_symbols.004_0']} />
          <mesh geometry={nodes.porsche_15.geometry} material={materials['TwiXeR_992_ID04_plastic_textured_001_060606FF.001']} />
          <mesh geometry={nodes.porsche_16.geometry} material={materials['TwiXeR_992_carpet.001']} />
          <mesh geometry={nodes.porsche_17.geometry} material={materials['TwiXeR_992_speakers.001']} />
          <mesh geometry={nodes.porsche_18.geometry} material={materials['TwiXeR_992_blackGlass.001']} />
          <mesh geometry={nodes.porsche_19.geometry} material={materials['TwiXeR_992_symbols_1.003']} />
          <mesh geometry={nodes.porsche_20.geometry} material={materials['TwiXeR_992_symbols.004_1']} />
          <mesh geometry={nodes.porsche_21.geometry} material={materials['TwiXeR_992_ID08_fabric_002.001']} />
          <mesh geometry={nodes.porsche_22.geometry} material={materials['TwiXeR_992_symbols.004_2']} />
          <mesh geometry={nodes.porsche_23.geometry} material={materials['TwiXeR_992_rivet_001_747474FF.001']} />
          <mesh geometry={nodes.porsche_24.geometry} material={materials['TwiXeR_992_headlight_1.001_2']} />
          <mesh geometry={nodes.porsche_25.geometry} material={materials['TwiXeR_992_seatbelt.001']} />
          <mesh geometry={nodes.porsche_26.geometry} material={materials['TwiXeR_992_plastic_1.001']} />
          <mesh geometry={nodes.porsche_27.geometry} material={materials['TwiXeR_992_gauges_chrome.001']} />
          <mesh geometry={nodes.porsche_28.geometry} material={materials['TwiXeR_992_int_chrome.003']} />
          <mesh geometry={nodes.porsche_29.geometry} material={materials.TwiXeR_992_GT3RS_black} />
          <mesh geometry={nodes.porsche_30.geometry} material={materials.TwiXeR_992_wheels_chrome_1} />
          <mesh geometry={nodes.porsche_31.geometry} material={materials['TwiXeR_992.001']} />
          <mesh geometry={nodes.porsche_32.geometry} material={materials['TwiXeR_992_exhausttip_antichrome.001']} />
          <mesh geometry={nodes.porsche_33.geometry} material={materials['TwiXeR_992_ID08_fabric_002_FFFFFFFF.003']} />
          <mesh geometry={nodes.porsche_34.geometry} material={materials['TwiXeR_992_engine.001']} />
          <mesh geometry={nodes.porsche_35.geometry} material={materials['TwiXeR_992_rubbertrim.008']} />
          <mesh geometry={nodes.porsche_36.geometry} material={materials['TwiXeR_992_int_chrome.005']} />
          <mesh geometry={nodes.porsche_37.geometry} material={materials['TwiXeR_992_ID03_stitch_001vents_a.003']} />
          <mesh geometry={nodes.porsche_38.geometry} material={materials['TwiXeR_992_rubbertrim.009']} />
          <mesh geometry={nodes.porsche_39.geometry} material={materials.TwiXeR_992_Interior_D} />
          <mesh geometry={nodes.porsche_40.geometry} material={materials.TwiXeR_992_ID06_stitch_001} />
          <mesh geometry={nodes.porsche_41.geometry} material={materials['TwiXeR_992_ID03_stitch_001_111111FF.005']} />
          <mesh geometry={nodes.porsche_42.geometry} material={materials['TwiXeR_992_carpet.002']} />
          <mesh geometry={nodes.porsche_43.geometry} material={materials.TwiXeR_992_ID01_plastic_lgl_010101FF} />
          <mesh geometry={nodes.porsche_44.geometry} material={materials.TwiXeR_992_symbols_6} />
          <mesh geometry={nodes.porsche_45.geometry} material={materials['TwiXeR_992_symbols_1.003_0']} />
          <mesh geometry={nodes.porsche_46.geometry} material={materials['TwiXeR_992_glass.004']} />
          <mesh geometry={nodes.porsche_47.geometry} material={materials['TwiXeR_992_glass_int.001']} />
          <mesh geometry={nodes.porsche_48.geometry} material={materials['TwiXeR_992_ID05_leather_coarse_mglshifterassy_a_2.002']} />
          <mesh geometry={nodes.porsche_49.geometry} material={materials['TwiXeR_992_rubbertrim.011']} />
          <mesh geometry={nodes.porsche_50.geometry} material={materials['TwiXeR_992_chrome.003']} />
          <mesh geometry={nodes.porsche_51.geometry} material={materials['TwiXeR_992_gauges_9000.001']} />
          <mesh geometry={nodes.porsche_52.geometry} material={materials['TwiXeR_992_ID03_stitch_001_111111FF.006']} />
          <mesh geometry={nodes.porsche_53.geometry} material={materials['TwiXeR_992_plastic.004']} />
          <mesh geometry={nodes.porsche_54.geometry} material={materials['TwiXeR_992_ID03_stitch_001vents_a.004']} />
          <mesh geometry={nodes.porsche_55.geometry} material={materials['TwiXeR_992_ID04_plastic_textured_001shifterassy_a.003']} />
          <mesh geometry={nodes.porsche_56.geometry} material={materials['TwiXeR_992_ID08_fabric_002centerconsolestructure_a.003']} />
          <mesh geometry={nodes.porsche_57.geometry} material={materials['TwiXeR_992_ID05_leather_coarse_mglvents_a.003']} />
          <mesh geometry={nodes.porsche_58.geometry} material={materials['TwiXeR_992_seat_leather.004']} />
          <mesh geometry={nodes.porsche_59.geometry} material={materials['TwiXeR_992_ID02_leather_MGL.003']} />
          <mesh geometry={nodes.porsche_60.geometry} material={materials['TwiXeR_992_gps_screen.003']} />
          <mesh geometry={nodes.porsche_61.geometry} material={materials['TwiXeR_992_upper_leather.004']} />
          <mesh geometry={nodes.porsche_62.geometry} material={materials['TwiXeR_992_plastic_2.003']} />
          <mesh geometry={nodes.porsche_63.geometry} material={materials['TwiXeR_992_gauges_1.003']} />
          <mesh geometry={nodes.porsche_64.geometry} material={materials['TwiXeR_992_gauges_9000.001_0']} />
          <mesh geometry={nodes.porsche_65.geometry} material={materials['TwiXeR_992_dash_clock_1.001']} />
          <mesh geometry={nodes.porsche_66.geometry} material={materials['TwiXeR_992_gauges_chrome_2.001']} />
          <mesh geometry={nodes.porsche_67.geometry} material={materials['TwiXeR_992_int_chrome.007']} />
          <mesh geometry={nodes.porsche_68.geometry} material={materials['TwiXeR_992_plastic_mgl_060606FF.002']} />
          <mesh geometry={nodes.porsche_69.geometry} material={materials['TwiXeR_992_ID09_rubbertrim_FFFFFFFF.002']} />
          <mesh geometry={nodes.porsche_70.geometry} material={materials['TwiXeR_992_ID04_plastic_textured_001_060606FF.002']} />
          <mesh geometry={nodes.porsche_71.geometry} material={materials['TwiXeR_992_ID05_leather_coarse_mgl_171717FF.002']} />
          <mesh geometry={nodes.porsche_72.geometry} material={materials['TwiXeR_992_speakers.002']} />
          <mesh geometry={nodes.porsche_73.geometry} material={materials['TwiXeR_992_antichrome.002']} />
          <mesh geometry={nodes.porsche_74.geometry} material={materials['TwiXeR_992_taillight_running.001']} />
          <mesh geometry={nodes.porsche_75.geometry} material={materials['TwiXeR_992_brakelight_1.002']} />
          <mesh geometry={nodes.porsche_76.geometry} material={materials['TwiXeR_992_plastic_smooth.001']} />
          <mesh geometry={nodes.porsche_77.geometry} material={materials['TwiXeR_992_led_lights.001']} />
          <mesh geometry={nodes.porsche_78.geometry} material={materials['TwiXeR_992_headlight_high.001']} />
          <mesh geometry={nodes.porsche_79.geometry} material={materials['TwiXeR_992_plastic_mgl.002']} />
          <mesh geometry={nodes.porsche_80.geometry} material={materials['TwiXeR_992_seat_leather_2.001']} />
          <mesh geometry={nodes.porsche_81.geometry} material={materials['TwiXeR_992_ID05_leather_coarse_mgl_FFFFFFFF.001']} />
          <mesh geometry={nodes.porsche_82.geometry} material={materials['TwiXeR_992_ID08_fabric_002_B60000FF.001']} />
          <mesh geometry={nodes.porsche_83.geometry} material={materials['TwiXeR_992_symbols_3.001']} />
          <mesh geometry={nodes.porsche_84.geometry} material={materials['TwiXeR_992_carPaint.008']} />
          <mesh geometry={nodes.porsche_85.geometry} material={materials['Scene_-_Root.002']} />
          <mesh geometry={nodes.porsche_86.geometry} material={materials['amdb11_caliper.002']} />
          <mesh geometry={nodes.porsche_87.geometry} material={materials['amdb11_misc_chrome.002']} />
          <mesh geometry={nodes.porsche_88.geometry} material={materials['amdb11_brake.002']} />
          </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/porsche_gt3_rs.glb");

function updateGeometries(wireframeMesh, texturedMesh, progress) {
  if (!wireframeMesh.geometry || !texturedMesh.geometry) return;

  const wireframePositionAttr = wireframeMesh.geometry.attributes.position;
  const texturedPositionAttr = texturedMesh.geometry.attributes.position;

  if (!wireframePositionAttr || !texturedPositionAttr) return;

  const threshold = Math.floor(progress * wireframePositionAttr.count);

  const wireframePositions = wireframePositionAttr.array;
  const texturedPositions = texturedPositionAttr.array;

  for (let i = 0; i < wireframePositions.length; i += 3) {
    const vertexIndex = i / 3;

    if (vertexIndex < threshold) {
      // Show this part in the textured mesh
      texturedPositions[i] = wireframePositions[i];
      texturedPositions[i + 1] = wireframePositions[i + 1];
      texturedPositions[i + 2] = wireframePositions[i + 2];
    } else {
      // Show this part in the wireframe mesh
      texturedPositions[i] = 0;
      texturedPositions[i + 1] = 0;
      texturedPositions[i + 2] = 0;
    }
  }

  // Mark the geometries as updated
  wireframePositionAttr.needsUpdate = true;
  texturedPositionAttr.needsUpdate = true;
}
